version: "3"
services:
  app:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: na_massa_web_development
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"