name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: na_massa_web_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/na_massa_web_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.1
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Install Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '19.2.0'
          cache: 'yarn'
      - name: Run bundles JS & CSS
        run: |
          yarn install
          yarn build
          yarn build:css
      - name: Run tests
        run: bundle exec rspec
