name: "Ruby on Rails CI"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
        with:
          bundler-cache: true
      # Add or replace database setup steps here
      - name: Set up database schema
        run: bin/rails db:schema:load
      # Add or replace test runners here
      - name: Run tests
        run: bundle exec rspec
# name: CI
# on: ["push", "pull_request"]

# jobs:
#   test:
#     runs-on: ubuntu-latest
#     services:
#       postgres:
#         image: postgres:11-alpine
#         ports:          
#           - "5432:5432"        
#         env:
#           POSTGRES_DB: na_massa_web_test
#     env:
#       RAILS_ENV: test
#       DATABASE_URL: "postgres://localhost:5432/na_massa_web_test"
#     steps:
#       - uses: actions/checkout@v3
#       - name: Set up Ruby
#         uses: ruby/setup-ruby@v1
#         with:
#           ruby-version: 3.2.1
#       - name: Install Node.js and Yarn
#         uses: actions/setup-node@v3
#         with:
#           node-version: '19.2.0'
#           cache: 'yarn'
#       - name: Install dependencies
#         run: |
#           gem install bundler
#           bundle install --jobs 4 --retry 3
#       - name: Create database
#         run: |
#           bundle exec rails db:create
#           bundle exec rails db:migrate
#       - name: Run bundles JS & CSS
#         run: |
#           yarn build
#           yarn build:css
#       - name: Run tests
#         run: |
#           bundle exec rspec